- src/AbstractVindiciaGateway.php
- src/Message/AbstractHOARequest.php
- src/Message/AbstractRequest.php
- src/Message/CaptureRequest.php
- src/Message/CaptureResponse.php
- src/Message/CompleteHOARequest.php
- src/Message/CompleteHOAResponse.php
- src/Message/CreatePayPalSubscriptionRequest.php
- src/Message/CreatePaymentMethodRequest.php
- src/Message/CreatePaymentMethodResponse.php
- src/Message/HOAAuthorizeRequest.php
- src/Message/HOACreatePaymentMethodRequest.php
- src/Message/HOACreateSubscriptionRequest.php
- src/Message/HOAPurchaseRequest.php
- src/Message/PayPalPurchaseRequest.php
- src/Message/PayPalPurchaseResponse.php
- src/Message/RefundRequest.php
- src/Message/Response.php
- src/TestFramework/Mocker.php
- tests/Message/AbstractRequestTest.php
- tests/Message/CreatePaymentMethodRequestTest.php
- tests/Message/HOACreatePaymentMethodRequestTest.php
- tests/Mock/CreatePaymentMethodNoCustomer228Success.xml
- tests/Mock/CreatePaymentMethodNoCustomerSuccess.xml
Just creates a payment method without attaching it to the customer object.
Includes better handling of multiple success codes that can come up when adding payment methods.
> Add support for adding a payment method without specifying the customer

- src/Message/Response.php
- src/ObjectHelper.php
- src/Subscription.php
- src/TestFramework/DataFaker.php
- tests/Message/CreatePayPalSubscriptionRequestTest.php
- tests/Message/CreateSubscriptionRequestTest.php
- tests/Message/FetchSubscriptionRequestTest.php
- tests/Mock/CreatePayPalSubscriptionSuccess.xml
- tests/Mock/CreateSubscriptionSuccess.xml
- tests/Mock/FetchSubscriptionSuccess.xml
Subscription billing state and status will help decide subscription's billing status. For example subscription status is active and billing state is "In Retry" it means subscription is active but in grace period.
cc @nickyr
> Add subscription billing state

- README.md
While `v2.*` will remain fully compatible with Omnipay 2, features added in addition to the base Omnipay features, such as subscriptions, may have breaking changes in a minor version bump. We should warn people of this.
> Add note recommending that people pin the minor version

- src/Message/RefundRequest.php
- src/Message/RefundResponse.php
- tests/Message/RefundRequestTest.php
Lets you can grab a `Refund` object from a refund response with `getRefund` instead of just getting a `stdClass`
> Use refund object instead of stdClass for refund response

- src/Chargeback.php
- src/Customer.php
- src/Message/Response.php
- src/ObjectHelper.php
- src/PaymentMethod.php
- src/Plan.php
- src/Product.php
- src/Refund.php
- src/Subscription.php
- src/Transaction.php
- src/VindiciaItem.php
- tests/ChargebackTest.php
- tests/CustomerTest.php
- tests/PaymentMethodTest.php
- tests/PlanTest.php
- tests/ProductTest.php
- tests/RefundTest.php
- tests/SubscriptionTest.php
- tests/TransactionTest.php
For better consistency with all other Omnipay functions.
**Changes:**
Transaction::getId -> Transaction::getTransactionId
Transaction::setId -> Transaction::setTransactionId
Transaction::getReference -> Transaction::getTransactionReference
Transaction::setReference -> Transaction::setTransactionReference
Subscription::getId -> Subscription::getSubscriptionId
Subscription::setId -> Subscription::setSubscriptionId
Subscription::getReference -> Subscription::getSubscriptionReference
Subscription::setReference -> Subscription::setSubscriptionReference
etc for all the other objects
The old way is still supported, but has been marked as deprecated
> Include object names in id/reference param names

- src/Message/FetchRefundsRequest.php
- src/Message/RefundRequest.php
- src/ObjectHelper.php
- src/Refund.php
- src/TestFramework/DataFaker.php
- tests/GatewayTest.php
- tests/Message/RefundRequestTest.php
- tests/Mock/RefundSuccess.xml
- tests/RefundTest.php
- tests/TestFramework/DataFakerTest.php
Because 'reason' makes more sense.
> Deprecate refund 'note' in favor of 'reason'

- src/TestFramework/DataFaker.php
- tests/GatewayTest.php
- tests/Message/AbstractRequestTest.php
- tests/Message/AuthorizeRequestTest.php
- tests/Message/CancelSubscriptionRequestTest.php
- tests/Message/CompleteHOARequestTest.php
- tests/Message/CreateCustomerRequestTest.php
- tests/Message/CreateSubscriptionRequestTest.php
- tests/Message/FetchPaymentMethodRequestTest.php
- tests/Message/PurchaseRequestTest.php
- tests/Message/RefundRequestTest.php
- tests/TestFramework/DataFakerTest.php
It's not really DataFaker's responsibility. This makes it easier for people to use the DataFaker for their own testing as well.
> Move timezone set from DataFaker to the tests

- src/Message/FetchSubscriptionsRequest.php
- tests/Message/FetchSubscriptionsRequestTest.php
- pageSize: The number of results to return. Will attempt to return up to 10000 if this parameter is not specified. This request will likely time out if there are that many records to return.
- page: The page number to return. Starts at 0. For example, if pageSize is 10 and page is 0, returns the first 10 results. If page is 1, returns the second 10 results. Defaults to 0.
> Add support for specifying page and pageSize for fetchSubscriptions

- src/Message/AbstractRequest.php
- src/Message/CompleteCreatePayPalSubscriptionRequest.php
- src/Message/CreatePayPalSubscriptionRequest.php
- src/Message/CreateSubscriptionRequest.php
- tests/Message/CreateSubscriptionRequestTest.php
Currently if you set a saved payment method ID with the CreateSubscriptionRequest, it always sets the type to credit card, so then Vindicia tries to validate the credit card and fails. Now, if you just provide a payment method ID and no other payment method details, a type won't be set so it will pass.
> Allow a saved PayPal payment method to be set on a subscription

- psalm_plugins/StringChecker.php
- src/Message/CreateSubscriptionRequest.php
- tests/Message/CreatePayPalSubscriptionRequestTest.php
- tests/Message/CreateSubscriptionRequestTest.php
This PR updates the default behavior for some subscription stuff to be more reasonable.
- Don't perform authorize when creating subscriptions by default. Instead, allow it to be set by a parameter.
- If a billing is scheduled for today and auth fails, put it into the retry cycle rather than just failing to create the subscription. Retrying is Vindicia's recommended behavior.
> Update subscription authorization behavior

- src/Message/CreateSubscriptionRequest.php
- tests/Message/CreateSubscriptionRequestTest.php
Only necessary for creating a new subscription
> Don't require customer or product ids/references for subscription update

- src/Message/CreateSubscriptionRequest.php
- tests/Message/CreateSubscriptionRequestTest.php
If we have no data to put in a subobject, we shouldn't create a subobject at all. This may be confusing Vindicia.
> Don't create empty soap subobjects on CreateSubscriptionRequest

- src/Message/CreateSubscriptionRequest.php
- tests/Message/CreateSubscriptionRequestTest.php
Adds retryIfInvalidPaymentMethod option which determines if the subscription be put into the retry cycle even if Vindicia thinks that the payment method is invalid. Defaults to false.
> Allow choice of whether to retry subscription if payment method is invalid

- tests/Message/FetchRefundsRequestTest.php
- tests/Message/FetchTransactionRequestTest.php
- tests/Message/FetchTransactionsRequestTest.php
- tests/Mock/FetchPayPalTransactionSuccess.xml
- tests/Mock/FetchRefundsByTimeSuccess.xml
- tests/Mock/FetchRefundsSuccess.xml
- tests/Mock/FetchTransactionByReferenceSuccess.xml
- tests/Mock/FetchTransactionSuccess.xml
- tests/Mock/FetchTransactionsByTimeSuccess.xml
- tests/Mock/FetchTransactionsSuccess.xml
Replace all hardcoded timestamps with the current timestamps. The hardcoded timestamp will cause the on demand tests in Vindicia response ticket to break, as transactions will be treated as already expired. Change them to be current timestamps will fix the broken unit tests in main repo.
> Fixed all hardcoded timestamps in mock response

- src/ObjectHelper.php
- src/PaymentMethod.php
- tests/Message/FetchPaymentMethodRequestTest.php
- tests/Message/FetchTransactionRequestTest.php
- tests/Mock/FetchTransactionSuccess.xml
- tests/PaymentMethodTest.php
Added sales tax address info to credit card shipping address field.
refactor objectHelper class to make the implementation clearer.
Remove redundant payment method getPostcode and getCountry methods
> Add sales tax address info to credit card shipping address field

- src/Message/CreatePaymentMethodRequest.php
- tests/Message/CreatePaymentMethodRequestTest.php
Add deactivate payment method option to create/update payment method request.
This is used in deactivate_payment_method script in main repo.
Since this is the only place possible to deactivate a payment method, we should enclose the changes only to this specific request.
> Add deactivate payment method option to create/update payment method request

- src/Message/CreatePaymentMethodRequest.php
- tests/Message/CreatePaymentMethodRequestTest.php
The payment method active flag is wrongly named 'activate' previously. So this PR fixes this issue.
> Fix payment method active flag

- src/Message/Response.php
Vindicia may mess up the return field if only one invoice num is returned. So we force it to return an array of string.
> Make the return value of response->getInvoiceReferences consistent

- src/Message/CalculateSalesTaxRequest.php
- src/Message/Response.php
- tests/Message/ResponseTest.php
This PR makes some small changes to better support the Avalara tax engine, which is the standard tax engine that is used with CashBox.
This includes two changes:
- Counts 202 return code as successful: Vindicia will return a 202 if the tax service goes down, but the transaction will still go through, so this should be counted as successful.
- If calculateSalesTax is called without customer, set a dummy value: The Avalara tax engine requires a customer to be set. Vindicia's advice if you don't want to do that is just to set a dummy value.
> Add support for Avalara tax engine

- src/Message/ApplePayAuthorizeRequest.php
Added `getValidationUrl()` in Apple Pay Request file so that we're getting all data needed to make an Apple Pay authorize call.
> Updated ApplePayAuthorizeRequest's getData

- src/Message/AbstractPageableRequest.php
- src/Message/FetchChargebacksRequest.php
- src/Message/FetchSubscriptionsRequest.php
- src/Message/FetchTransactionsRequest.php
- tests/Message/FetchChargebacksRequestTest.php
When fetching chargebacks in a date range, you can now specify a page size and page number to fetch, instead of fetching all at once.
I created an AbstractPageableRequest to contain paging logic since there are several requests that support paging. I would have done a trait, but Omnipay 2 supports versions of PHP that don't support traits.
> Add support for paging to fetchChargebacks request

- src/Message/AbstractRequest.php
- src/Message/ApplePayAuthorizeRequest.php
- tests/EventEmitterTest.php
* Quick fix to update the `ErrorEvent` constructor to take in the new required request object param.
> Update ErrorEvent instantiation to include request object

- src/ApplePayGateway.php
- src/Message/AbstractRequest.php
- src/Message/ApplePayCompleteAuthorizeRequest.php
- src/NonStrippingCreditCard.php
- src/TestFramework/DataFaker.php
- tests/ApplePayGatewayTest.php
- tests/Message/ApplePayCompleteAuthorizeRequestTest.php
- tests/Message/FetchPaymentMethodRequestTest.php
- tests/Mock/ApplePayCompleteAuthorizeRequestSuccess.xml
- tests/NonStrippingCreditCardTest.php
- Updates `Message\AbstractRequest` for ApplePay completeAuthorize compatibility.
- Adds new `ApplePayCompleteAuthorizeRequest` file.
- Adds tests and mockfile for `ApplePayCompleteAuthorizeRequest`.
- Changed NonstrippingCreditCard's comment for token. 
_(Previous token is actually paymentData that is apart of the Apple Pay token.)_
> Add support for completeAuthorize and capture for Apple Pay.

- src/Message/Response.php
This PR changes `Response::getSoapId()` to return null instead of throwing an error.
> Modifies getSoapId to return null

- .travis.yml
- tests/Mock/CreateSubscriptionSuccess.xml
Allows custom values for `merchantProductId` on the autobill item in the `CreateSubscriptionSuccess` mock response. Intended for use with actual Vimeo product ids, which will enable unit testing certain features that require valid autobill items to be created from a Vindicia response.
> Allow custom merchant product ID in success response mock

- .travis.yml
- composer-psalm.json
- src/Message/CancelSubscriptionRequest.php
- src/Message/CancelSubscriptionsRequest.php
- src/Message/FetchSubscriptionRequest.php
- src/Message/Response.php
- src/ObjectHelper.php
- src/Subscription.php
- src/TestFramework/DataFaker.php
- tests/Message/CancelSubscriptionRequestTest.php
- tests/Message/CancelSubscriptionsRequestTest.php
- tests/Mock/CancelSubscriptionSuccess.xml
- tests/SubscriptionTest.php
- tests/TestFramework/DataFakerTest.php
Vindicia subscriptions can have a cancellation reason when they get canceled. Sometimes, Vindicia will specify the reason. The merchant can also specify the reason if they make a call to cancel the subscription.
This PR adds support for setting and retrieving the cancel reason to this library.
Vindicia docs about cancel reasons: https://www.vindicia.com/documents/1800APIGuideHTML5/Default.htm#APIGuide/CancelReason_Subobject1.htm%3FTocPath%3DCashBox1800APIGuide%7C4%2520The%2520AutoBill%2520Object%7CAutoBill%2520Subobjects%7C_____4
And here are the possible values: https://www.vindicia.com/documents/2500ProgGuideHTML5/Default.htm#ProgGuide/Canceling_AutoBills_with.htm%3FTocPath%3DCashBox2500ProgGuide%7C5%2520Working%2520with%2520AutoBills%7C5.3%2520Canceling%2520AutoBills%7C_____1
> Allow a subscription cancellation reason to be set and retrieved

- src/Message/AbstractRequest.php
- tests/Message/AbstractRequestTest.php
Fixes a bug that would set a default tax classification as TAX_EXEMPT on update.  The default should only be set when creating new products, not on updates.
> Fix bug that defaults tax classification on update

- src/Message/PurchaseRequest.php
Adds ability to set whether to ignore AVS/CVN policies in `PurchaseRequest`.
> Allow disabling purchase AVS/CVN policy on purchase

- src/ObjectHelper.php
- src/Refund.php
According to [Vindicia documentation](https://www.vindicia.com/documents/1800APIGuideHTML5/Default.htm#APIGuide/Refund_Data_Members.htm%3FTocPath%3DCashBox1800APIGuide%7C15%2520The%2520Refund%2520Object%7C_____1) Refund objects have a status field which can be any of the following: Reported, Processing, Failed, Complete.
> Add status to Refund object

- src/Message/AbstractRequest.php
- src/Message/CreateSubscriptionRequest.php
- tests/Message/AbstractRequestTest.php
We never actually made use of the subscription qty when creating a subscription on Vindicia. This PR makes sure that the quantity is set
> Set product qty

- src/ObjectHelper.php
- src/TestFramework/DataFaker.php
- tests/Mock/FetchTransactionByReferenceSuccess.xml
- tests/ObjectHelperTest.php
- tests/VindiciaItemTest.php
Updates the` ObjectHelper->buildTransaction()` method to assign `autoBillItemVid` values.
> Assign autoBillItemVid values to transaction items

- src/Message/PayPalAuthRequest.php
- src/Message/PayPalAuthorizeRequest.php
- src/Message/PayPalAuthorizeResponse.php
- src/PayPalGateway.php
- tests/Message/PayPalAuthorizeRequestTest.php
- tests/Message/PayPalAuthorizeResponseTest.php
- tests/Mock/PayPalAuthorizeFailure.xml
- tests/Mock/PayPalAuthorizeSuccess.xml
- tests/PayPalGatewayTest.php
This can be used to authorize a PayPal payment method before starting a free trial.
There is a lot of new stuff but is heavily based on existing tests and mock responses for `PayPalPurchaseRequest`.
> Add PayPalGateway::authorize

- src/TestableSoapClient.php
This can be used to setup a soap call exception as part of a test without having to mock `TestableSoapClient` with a Mockery overload prefix (or something similar). Instead, `TestableSoapClient::setNextResponse` can be used to set the desired exception as the next "response".
> Allow queued throwables from test soap calls

- src/ObjectHelper.php
When the transaction's payment method is `PayPal` the `authCode` is found in the `payPalStatus` property instead of the `creditCardStatus` property. This PR retrieves the `authCode` from the `payPalStatus` property if the he `creditCardStatus` property does not exist.
> include paypal authcodes in transactions object

- src/ObjectHelper.php
- src/PaymentMethod.php
Include paypal email in payment method to avoid retrieving it from the transaction
> include paypal email in payment method
